### PR TITLE
Remove Unused Dependencies: six, python-dateutil 

### PR DESCRIPTION
**Pull request by gdrosos**
**Summary:**

This pull request addresses the removal of the unused dependencies `six` and `python-dateutil` from the project. It's part of an ongoing research endeavor focusing on the identification and elimination of code bloat within software projects. 

**Rationale:**

The `six` dependency was intorduced on commit ec2b092 for its use on `edx_rest_framework_extensions/tests/test_paginators.py`. However, it was removed form the source code on 21f98ec, wghile still being declared as a direct dependency in the configuration files. 

Similarly, the `python-dateutil` dependency, was introduced in the project on b41a017 for its use on `edx_rest_framework_extensions/authentication.py`. However, it was removed on b9c2e61.

Removing these unused dependencies contributes to a leaner codebase, reduces security risks, and simplifies dependency management. 

**Changes:**

- Removed `six` and `python-dateutil` dependencies from `base.in`.
- Updated `base.txt`, `test.txt`, `dev.txt`  to reflect the removed dependencies.

**Impact:**

- Enhanced Project Maintainability: Treating `six` and `python-dateutil` only as transitive dependencie ensures a cleaner and more maintainable codebase.
- Streamlined Dependency Tree: By optimizing the direct dependencies, we reduce potential security vulnerabilities and enhance the project's overall robustness.
- Improved Development Efficiency: Simplifying the dependency management process speeds up project setup and ensures that only necessary dependencies are included.

I also signed the Contributor License Agreement (CLA) according to the contributing [guidelines](https://github.com/openedx/.github/blob/aa20ddc6976eb7ec6c1a6de5ad86f644198a9667/CONTRIBUTING.md)

**Additional Details**

* **Dependencies:**: List dependencies on other outstanding PRs, issues, etc.
* **Merge deadline:** List merge deadline (if any)
* **Testing instructions:** Provide non-trivial testing instructions
* **Author concerns:** List any concerns about this PR

**Reviewers:**
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bump if needed
- [x] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gdrosos!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by e0d** [comment]
@gdrosos  Thanks for your contribution.  I hope you saw the message about your CLA. If this contribution is made as an individual, we need to associate the CLA with an email that isn't related to a university, firm, or other type of organization.

I alsonotice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by gdrosos** [comment]
Thanks @e0d, I resubmitted it.

**Comment by e0d** [comment]
@gdrosos Excellent, I'll look out for it.  In the meantime could you ammend the commit messages to use our conventional commit standard?

**Comment by gdrosos** [comment]
Thanks @e0d, I force-pushed the commits in order to follow the conventional commit standard. Moreover, I signed the CLA. 

Please let me know if there is anything else I need to do.

**Comment by e0d** [comment]
Hi @gdrosos.  We're having some config issues with the system for managing CLAs.  They CLA I sent you yesterday, had your prior email address.  I've tried to send a copy with the correct information this morning.  Please let me know if you see it and it looks correct.

**Comment by gdrosos** [comment]
Hello @e0d, I signed the new CLA.

**Comment by e0d** [comment]
Re-running the check.

**Comment by e0d** [comment]
CLA check.

**Review by awais786 — APPROVED** [review]

**Comment by UsamaSadiq** [comment]
@gdrosos please resolve the conflicts so I'll be able to merge the PR.

**Comment by gdrosos** [comment]
Thank you @UsamaSadiq, I resolved the conflict on 2a8a102

**Comment by gdrosos** [comment]
Thank you @UsamaSadiq, on ad6a6b6 I resolved the conflicts.

**Comment by openedx-webhooks** [comment]
@gdrosos 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-drf-extensions&entry.867055334=https://github.com/openedx/edx-drf-extensions/pull/377&entry.1484655318=https://github.com/gdrosos&entry.752974735=2023-09-04+09:21&entry.1917517419=2023-09-08+13:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
